import http from 'node:http';import {readFile} from 'node:fs/promises';import path from 'node:path';import {fileURLToPath} from 'node:url';import {Store,id} from './store.mjs';import {analyze,validateProgram,validateVariant,validateComponent} from './engine.mjs';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),store=new Store(path.resolve(process.env.DATA_DIR||path.join(root,'data')));await store.init();const port=Number(process.env.PORT||3000);const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json'};
async function body(req){let x='';for await(const c of req){x+=c;if(x.length>2e6)throw Object.assign(new Error('Request too large'),{status:413})}return x?JSON.parse(x):{}}function send(res,status,x,type='application/json; charset=utf-8'){res.writeHead(status,{'content-type':type,'cache-control':'no-store','x-content-type-options':'nosniff','x-frame-options':'DENY'});res.end(type.startsWith('application/json')?JSON.stringify(x):x)}function audit(p,action,actor='user',detail={}){p.audit.push({id:id(),at:new Date().toISOString(),action,actor,detail})}
async function route(req,res){const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/api/health')return send(res,200,{status:'ok',service:'VariantGuard',time:new Date().toISOString()});if(req.method==='GET'&&u.pathname==='/api/programs')return send(res,200,(await store.list()).map(p=>({id:p.id,name:p.name,release:p.release,owner:p.owner,updatedAt:p.updatedAt,variants:p.variants.length,components:p.components.length,analyses:p.analyses.length})));
 if(req.method==='POST'&&u.pathname==='/api/programs'){const x=await body(req),errors=validateProgram(x);if(errors.length)return send(res,400,{errors});const p=await store.create({name:x.name.trim(),release:x.release.trim(),owner:x.owner.trim(),description:x.description||'',variants:[],components:[],tests:[],analyses:[],reviews:[],audit:[]});audit(p,'PROGRAMME_CREATED',p.owner);await store.save(p);return send(res,201,p)}
 const m=u.pathname.match(/^\/api\/programs\/([a-f0-9-]+)(?:\/(variants|components|tests|analyses|reviews|report))?$/i);if(m&&req.method==='GET'&&!m[2])return send(res,200,await store.get(m[1]));if(!m)return req.method==='GET'?staticFile(u,res):send(res,404,{error:'Not found'});const p=await store.get(m[1]);if(req.method==='GET'&&m[2]==='report')return send(res,200,{schemaVersion:'1.0',programme:p,latestAnalysis:p.analyses.at(-1)||null});if(req.method!=='POST')return send(res,405,{error:'Method not allowed'});const x=await body(req);
 if(m[2]==='variants'){const errors=validateVariant(x);if(errors.length)return send(res,400,{errors});const v={id:id(),name:x.name.trim(),platform:x.platform.trim(),hardware:x.hardware.trim(),os:x.os.trim(),middleware:x.middleware.trim(),features:x.features||[],components:x.components||[],safetyLevel:x.safetyLevel||'QM'};p.variants.push(v);audit(p,'VARIANT_ADDED',x.actor,{variantId:v.id})}
 if(m[2]==='components'){const errors=validateComponent(x);if(errors.length)return send(res,400,{errors});const c={id:id(),name:x.name.trim(),version:x.version.trim(),owner:x.owner.trim(),tags:x.tags||[],constraints:x.constraints||{}};p.components.push(c);audit(p,'COMPONENT_ADDED',x.actor,{componentId:c.id})}
 if(m[2]==='tests'){if(!x.name?.trim()||!x.kind?.trim())return send(res,400,{error:'Test name and kind are required.'});const t={id:id(),name:x.name.trim(),kind:x.kind.trim(),level:x.level||'COMPONENT',tags:x.tags||[],componentIds:x.componentIds||[],platforms:x.platforms||[]};p.tests.push(t);audit(p,'TEST_ADDED',x.actor,{testId:t.id})}
 if(m[2]==='analyses'){if(!x.title?.trim()||!x.componentId)return send(res,400,{error:'Change title and component are required.'});const input={id:id(),createdAt:new Date().toISOString(),title:x.title.trim(),componentId:x.componentId,changeType:x.changeType||'MINOR',changedTags:x.changedTags||[],cybersecurityRelevant:Boolean(x.cybersecurityRelevant),includeCompatibleCandidates:Boolean(x.includeCompatibleCandidates)};const a=analyze(p,input);p.analyses.push(a);audit(p,'IMPACT_ANALYSIS_RUN',x.actor,{analysisId:a.id,decision:a.decision})}
 if(m[2]==='reviews'){if(!x.reviewer?.trim()||!['APPROVED','REWORK','REJECTED'].includes(x.disposition))return send(res,400,{error:'Reviewer and valid disposition are required.'});const r={id:id(),analysisId:x.analysisId||p.analyses.at(-1)?.id,reviewer:x.reviewer.trim(),disposition:x.disposition,notes:x.notes||'',at:new Date().toISOString()};p.reviews.push(r);audit(p,'REVIEW_RECORDED',r.reviewer,{reviewId:r.id,disposition:r.disposition})}
 await store.save(p);return send(res,200,p)}
async function staticFile(u,res){const f=u.pathname==='/'?'index.html':u.pathname.replace(/^\/+/,''),target=path.join(root,'public',path.normalize(f));if(!target.startsWith(path.join(root,'public')))return send(res,403,{error:'Forbidden'});try{return send(res,200,await readFile(target),mime[path.extname(target)]||'application/octet-stream')}catch{return send(res,404,{error:'Not found'})}}
http.createServer((req,res)=>route(req,res).catch(e=>{console.error(e);send(res,e.status||500,{error:e.message||'Unexpected error'})})).listen(port,'0.0.0.0',()=>console.log(`VariantGuard listening on ${port}`));
